---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks.git
      rev: "v4.4.0"
      hooks:
          - id: check-added-large-files
          - id: check-merge-conflict
          - id: check-executables-have-shebangs
          - id: end-of-file-fixer
    - repo: https://github.com/pre-commit/mirrors-prettier.git
      rev: "v3.0.1"
      hooks:
          - id: prettier
            name: "apply code formatting"
