name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  ubuntu-clang-trinitycore:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: ./.github/actions/setup_ubuntu
      - name: Install Boost
        id: install-boost
        uses: MarkusJx/install-boost@v2.3.0
        with:
          boost_version: 1.79.0
      - name: Build tswow
        shell: bash
        run: npm run build noac BOOST_ROOT=${{ steps.install-boost.outputs.BOOST_ROOT }}

  windows-msvc-trinitycore:
    runs-on: windows-2019
    steps:
      # Build
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: ./.github/actions/setup_windows
      - name: Build tswow
        run: npm run build-release clean-archives noac tracy=*
      - uses: ./.github/actions/publish_windows
        env:
          TSWOW_UPLOAD_URL: ${{secrets.TSWOW_UPLOAD_URL}}
          EVENT_NAME: ${{github.event_name}}
        if: "${{ env.TSWOW_UPLOAD_URL != '' && env.EVENT_NAME != 'pull_request'}}"
        with:
          core: 'trinitycore'
          token: ${{secrets.GITHUB_TOKEN}}
          upload-url: ${{ secrets.TSWOW_UPLOAD_URL }}

  #windows-msvc-azerothcore:
  #  runs-on: windows-2019
  #  steps:
  #    # Build
  #    - uses: actions/checkout@v2
  #      with:
  #        submodules: 'recursive'
  #    - uses: ./.github/actions/setup_windows
  #    - name: Build tswow
  #      run: npm run build-release clean-archives notc
  #    - uses: ./.github/actions/publish_windows
  #      env:
  #        TSWOW_UPLOAD_URL: ${{ secrets.TSWOW_UPLOAD_URL }}
  #        EVENT_NAME: ${{github.event_name}}
  #      if: "${{ env.TSWOW_UPLOAD_URL != '' && env.EVENT_NAME != 'pull_request'}}"
  #      with:
  #        core: 'azerothcore'
  #        token: ${{secrets.GITHUB_TOKEN}}
  #        upload-url: ${{ secrets.TSWOW_UPLOAD_URL }}